[phases.setup]
nixPkgs = ["php74", "php74Extensions.mysqli", "php74Extensions.mbstring", "php74Extensions.xml", "php74Extensions.curl", "php74Extensions.zip", "php74Extensions.gd", "php74Extensions.pdo_mysql"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[start]
cmd = "php -S 0.0.0.0:${PORT:-8080} index.php"
